/* Plugin Template generated by Pawn Studio */
#include <sourcemod>
#include <sdktools>
#include "include/modules/baseplugin.sp"
#define PLUGIN_SKILL_NAME "Nightvision"
#define PLUGIN_DESCRIPTION  "Provides Nightvision goggles"
new IMPULS_FLASHLIGHT = 100;
new Float:PressTime[MAXPLAYERS+1];
 
new Mode; 
new bool:EnableSuvivor; 
new bool:EnableInfected; 
new Handle:l4d_nt_team;

public Plugin:myinfo = 
{
	name = "[DLR] Nightvision Plugin",
	author = "Pan Xiaohai & Mr. Zero, Yani",
	description = PLUGIN_DESCRIPTION,
	version = "1.0",
	url = "<- URL ->"
}

int g_iSlotSpecial;
int g_iLevelNVG[MAXPLAYERS+1];

public OnPluginStart()
{
	RegConsoleCmd("sm_nightvision", sm_nightvision);
	l4d_nt_team = CreateConVar("l4d_nt_team", "1", " 0:disable, 1:enable for survivor and infected, 2:enable for survivor, 3:enable for infected ");	
	AutoExecConfig(true, "l4d_nightvision"); 
	HookConVarChange(l4d_nt_team, ConVarChange);
	GetConVar();
		
	HookEvent("player_spawn", Event_PlayerSpawn);
	HookEvent("player_first_spawn", Event_PlayerSpawn);
	
	g_iSlotSpecial = DLR_RegSlot("special");
	DLR_RegPerk(g_iSlotSpecial, "night_vision", 1, 25, 5, 2.0);
}

public Action DLR_OnGetPerkName(int client, const char[] name, int level, char[] result, int maxlen)
{
	if(!strcmp(name, "night_vision"))
		FormatEx(result, maxlen, "Night Vision", client, level);
	else
		return Plugin_Continue;
	return Plugin_Changed;
}

public Action DLR_OnGetPerkDescription(int client, const char[] name, int level, char[] result, int maxlen)
{
	if(!strcmp(name, "night_vision"))
		FormatEx(result, maxlen, PLUGIN_DESCRIPTION);
	else
		return Plugin_Continue;
	return Plugin_Changed;
}

public void DLR_OnPerkPost(int client, int level, const char[] perk)
{
	if(!strcmp(perk, PLUGIN_SKILL_NAME))
		g_iLevelNVG[client] = level;
}

public void DLR_OnLoad(int client)
{
	g_iLevelNVG[client] = DLR_GetClientPerk(client, "night_vision");
}

public void Event_PlayerSpawn(Event event, const char[] eventName, bool dontBroadcast)
{
	int client = GetClientOfUserId(event.GetInt("userid"));
	if(!IsValidClient(client))
		return;
	
	g_iLevelNVG[client] = DLR_GetClientPerk(client, "night_vision");
}

int IntBound(int v, int min, int max)
{
	if(v < min)
		v = min;
	if(v > max)
		v = max;
	return v;
}

public ConVarChange(Handle:convar, const String:oldValue[], const String:newValue[])
{
	GetConVar(); 
}
GetConVar()
{
	Mode=GetConVarInt(l4d_nt_team);
	EnableSuvivor=(Mode==1 || Mode==2);
	EnableInfected=(Mode==1 || Mode==3);
}
public Action:sm_nightvision(client,args)
{
	if(IsClientInGame(client))SwitchNightVision(client);
}
//code from "Block Flashlight",
public Action:OnPlayerRunCmd(client, &buttons, &impuls, Float:vel[3], Float:angles[3], &weapon)
{
	if(Mode==0 || g_iLevelNVG[client] < 1)return;	
	if(impuls==IMPULS_FLASHLIGHT)
	{
		new team=GetClientTeam(client);
		if(team==2 && EnableSuvivor )
		{		 	
			new Float:time=GetEngineTime();
			if(time-PressTime[client]<0.3)
			{
				SwitchNightVision(client); 				 
			}
			PressTime[client]=time; 
			 
		}	 
		if(team==3 && EnableInfected)
		{				
			new Float:time=GetEngineTime();
			if(time-PressTime[client]>0.1)
			{
				SwitchNightVision(client); 
			}
			PressTime[client]=time;			 
		}
	}
}
SwitchNightVision(client)
{
	new d=GetEntProp(client, Prop_Send, "m_bNightVisionOn");
	if(d==0)
	{
		SetEntProp(client, Prop_Send, "m_bNightVisionOn",1); 
		PrintHintText(client,"Night Vision ON", client);
		
	}
	else
	{
		SetEntProp(client, Prop_Send, "m_bNightVisionOn",0);
		PrintHintText(client, "Night Vision OFF", client);	
	}
}
